development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: pillow_development
  pool: 5
  username: postgres
  password:
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: pillow_test
  pool: 5
  username: postgres
  password:
  port: 5432

staging:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: pillow_staging
  pool: 5
  username: postgres
  password:
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: pillow_production
  pool: 5
  username: postgres
  password:
  port: 5432